export enum FeatureFlag {
  MENU_VIEW = 'menu:view',
  MENU_EDIT = 'menu:edit',
  MENU_IMPORT = 'menu:import',
  QR_MANAGE = 'qr:manage',
  ORDERS_RECEIVE = 'orders:receive',
  ORDERS_CALL_WAITER = 'orders:call-waiter',
  ANALYTICS_BASIC = 'analytics:basic',
  ANALYTICS_FULL = 'analytics:full',
  PAYMENTS_EPAY = 'payments:epay',
  PAYMENTS_BORICA = 'payments:borica',
  PAYMENTS_MYPOS = 'payments:mypos',
  PAYMENTS_STRIPE = 'payments:stripe',
  LANGUAGES_MULTI = 'languages:multi',
  BRANDING_CUSTOM = 'branding:custom',
  LOYALTY = 'loyalty',
  CUSTOMERS_AUTH = 'customers:auth',
  UPSELLING = 'upselling',
  DAYPARTING = 'dayparting',
  POS = 'pos',
  KDS = 'kds',
  RBAC = 'rbac',
  MULTILOCATION = 'multilocation',
  PRINTERS_THERMAL = 'printers:thermal',
  TEMPLATES_MENU = 'templates:menu',
  STAFF_UNLIMITED = 'staff:unlimited',
}
