import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: "doc",
      id: "getting-started",
      label: "Getting Started",
    },
    {
      type: "autogenerated",
      dirName: "guides",
    },
  ],

  adminSidebar: [
    {
      type: "autogenerated",
      dirName: "admin",
    },
  ],

  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};

export default sidebars;
