ALTER TABLE "restaurant"
  ADD COLUMN IF NOT EXISTS "happyHourDays" INTEGER[] NOT NULL DEFAULT ARRAY[1,2,3,4,5,6,7]::INTEGER[];

ALTER TABLE "restaurant"
  ADD COLUMN IF NOT EXISTS "websiteUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "youtubeUrl" TEXT;
